version: '3.8'

services:
  weather-exporter:
    build: .
    ports:
      - "9090:9090"
    environment:
      # REQUIRED: Set your unique User-Agent
      - WEATHER_USER_AGENT=${WEATHER_USER_AGENT:-MUST_BE_SET}
      - WEATHER_LOCATIONS=${WEATHER_LOCATIONS:-Oslo,Stockholm,Copenhagen}
      - PORT=9090
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped

volumes:
  prometheus_data:
